{% set name = "databases" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e3b21a237d8b8a8774da1237fa75e951e23bf8e943516df8fe2443f1968287f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sqlalchemy >=1.3.0
    - aiocontextvars  # [py<37]
    - asyncpg
    - psycopg2
    - aiomysql
    - pymysql
    - aiosqlite

test:
  imports:
    - databases

about:
  home: https://github.com/encode/databases/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Async database support for Python. 🗄
  description: |
    Databases gives you simple asyncio support for a range of databases.

    It allows you to make queries using the powerful SQLAlchemy Core expression 
    language, and provides support for PostgreSQL, MySQL, and SQLite.
  doc_url: https://github.com/encode/databases/
  dev_url: https://github.com/encode/databases/

extra:
  recipe-maintainers:
    - carlodri
