travis:
  secure:
    BINSTAR_TOKEN: R01wcO2oArYZtuM4SYLz9ZeM6M4ZTndX47xz4vsL8bGYKgJcDRiqPqSJorxCDrHi5NqG5ifXGNdEEuJ10b5iAq/YGqeBKKqObuY8rEd8kM1SDnSi2HAEFh1SJvmusUsLQBi2tc6mqFR54nF26ZODeRM9yfE+aqinAr6iDFRn8cui4iMGrCcECQRtCU94RFswRXSOnAxvbMGEAl35sxHRyPiVXrZ9ntRromqphj/Hayds5f0LzKyERrTZv+cdz9kJUINQbRfYXULKcvJI4nISQ960yWc5TgYIX8WvmgEfr9ALMrok8Nd/2RIN4eY14TlVtwml0bcTuMYPOcN3FwVpHpbsAQoAUXGf6Q2wTMTmlJPSNBnoLH3wwP19xTnwO6222qau4L1jSwmsYnLlHPMsLRIHDI972zB2L7t/ktId37yfYwlmVPCJ5TG20Dj/N6aS2GEXy6wWrNrxbyp90lKYHt9UCPgqCyfoww+XVfTjk1ho019mGJ/3aN3ZIXxyZmjIzMLJpfLbnIMTAfWhwnhdSkA8iF/R+uGoosL6aHLFZqI76OOtPdhScEg/SRQjpvcQIi8FsMwusR62RQOGi//Ms5rw4Kmls37lRNORB+Ld2vtWSFj4N4wUDfseGHHEltND/NEMWHBZgyOeO6tTIqD5E8oq8iN1BsaEKYp9JRaniAY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
